// Patch de relatórios por link — Web/Mobile + tipos de relatório
(function(){
let relVersao='mobile';
const T={visao:'Visão Geral atual',alunos:'Relatório geral dos alunos',modulo:'Relatório por módulo',turma:'Relatório por turma',caminho:'Grade do caminho do aluno'};
function patchUI(){
 const p=document.getElementById('page-exportar'); if(!p||document.getElementById('exp-tipo')) return;
 p.innerHTML=`<div class="stitle">📤 Gerar Relatório <small>por link, sem baixar arquivo</small></div>
 <div class="card" style="margin-bottom:20px"><div class="form-row tri">
 <div><label>Título do Relatório</label><input id="exp-titulo" value="Instituto de Vencedores"></div>
 <div><label>Tipo de Relatório</label><select id="exp-tipo"><option value="visao">📊 Visão Geral atual</option><option value="alunos">🎓 Relatório geral dos alunos</option><option value="modulo">📘 Relatório por módulo</option><option value="turma">🏫 Relatório por turma</option><option value="caminho">🧭 Grade do caminho do aluno</option></select></div>
 <div><label>Módulo</label><select id="exp-modulo"><option value="todos">Todos os Módulos</option><option value="1">1º Módulo</option><option value="2">2º Módulo</option><option value="3">3º Módulo</option></select></div>
 </div><div class="form-row"><div><label>Versão do relatório</label><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:6px"><button class="ptab active" id="tab-mobile" onclick="setVersaoRelatorio('mobile',this)">📱 Mobile</button><button class="ptab" id="tab-web" onclick="setVersaoRelatorio('web',this)">💻 Web</button></div></div>
 <div id="device-mobile-box"><label>Dispositivo mobile</label><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:6px"><button class="ptab active" id="tab-android" onclick="setDisp('android',this)">📱 Android</button><button class="ptab" id="tab-iphone" onclick="setDisp('iphone',this)">🍎 iPhone</button></div></div></div></div>
 <div class="export-grid"><div class="export-card" onclick="gerarRelatorioLink()"><div class="export-icon">🔗</div><div class="export-name">Gerar Link do Relatório</div><div class="export-desc">Escolha o tipo de relatório e a versão Web ou Mobile. O sistema gera um link para compartilhar no WhatsApp, sem baixar arquivo HTML.</div></div>
 <div id="modal-link" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:9000;align-items:center;justify-content:center;padding:20px"><div style="background:#0D1626;border:1px solid #1E2E4A;border-radius:16px;padding:28px;max-width:520px;width:100%"><div style="font-size:18px;font-weight:700;color:#fff;margin-bottom:8px">🔗 Link gerado!</div><div style="font-size:13px;color:#6B8AB0;margin-bottom:14px">Mensagem que será enviada no WhatsApp:</div><div id="whats-preview" style="background:#0A2E1A;border:1px solid #1E5C36;border-radius:10px;padding:12px 14px;font-size:13px;color:#E8F0FF;white-space:pre-line;line-height:1.6;margin-bottom:14px;font-family:'DM Sans',sans-serif"></div><input id="link-gerado" readonly style="display:none"><div style="display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap"><button class="btn btn-ghost" onclick="document.getElementById('modal-link').style.display='none'">Fechar</button><button class="btn btn-blue" onclick="copiarLink()">📋 Copiar mensagem</button><button class="btn btn-green" onclick="abrirWhatsApp()">📲 Abrir WhatsApp</button><button class="btn btn-ghost" onclick="window.open(document.getElementById('link-gerado').value,'_blank')">🌐 Abrir link</button></div></div></div></div>
 <div class="card" style="margin-top:20px"><div class="card-title">💾 Backup de Dados</div><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center"><button class="btn btn-ghost" onclick="exportarDados()">⬇️ Baixar Backup JSON</button><label class="btn btn-ghost" style="cursor:pointer">⬆️ Carregar Backup<input type="file" accept=".json" style="display:none" onchange="importarDados(this)"></label></div><p style="font-size:12px;color:var(--muted);margin-top:10px">O backup salva todos os alunos, equipes e presenças. Os relatórios agora são gerados por link.</p></div>`;
}
window.setVersaoRelatorio=function(t,b){relVersao=t;document.querySelectorAll('#tab-mobile,#tab-web').forEach(x=>x.classList.remove('active'));if(b)b.classList.add('active');let box=document.getElementById('device-mobile-box');if(box)box.style.display=t==='mobile'?'block':'none'};
function turma(v){return v==='quinta'?'Quinta-feira':v==='sabado'?'Sábado':'Sem turma'}
function eq(a){let e=(DB.equipes||[]).find(x=>x.id===a.equipeId);return e?e.nome:'Sem equipe'}
function total(m){return MODULOS[m].semanas.reduce((n,s)=>n+s.aulas.length,0)}
function st(a,m){let p=0,t=total(m),at=parseInt(a.modulo||'1');MODULOS[m].semanas.forEach((s,si)=>s.aulas.forEach(au=>{if(DB.presencas[presKey(a.id,m,si,au)])p++}));let conta=m<=at||p>0,f=conta?Math.max(t-p,0):0,status=m<at?'Concluído':m===at?'Módulo ativo':p>0?'Iniciado':'Próximo módulo';return{p,t,f,pct:t?Math.round(p/t*100):0,status}}
function rows(mod){return (DB.alunos||[]).filter(a=>mod==='todos'||String(a.modulo||'1')===String(mod)).map(a=>{let at=parseInt(a.modulo||'1'),mods=[1,2,3].map(m=>st(a,m)),pres=mods.reduce((s,x)=>s+x.p,0),faltas=mods.reduce((s,x)=>s+x.f,0),tt=mods.reduce((s,x)=>s+x.t,0);return{nome:a.nome||'—',ins:a.inscricao||'',mod:MODULOS[at]?MODULOS[at].nome:at+'º Módulo',at,equipe:eq(a),turma:turma(a.turma),sit:a.situacao||'ATIVO',mods,pres,faltas,pct:tt?Math.round(pres/tt*100):0}}).sort((a,b)=>a.at-b.at||a.nome.localeCompare(b.nome,'pt-BR'))}
function grup(r,fn){let o={};r.forEach(a=>(o[fn(a)]=o[fn(a)]||[]).push(a));return Object.entries(o).sort((a,b)=>b[1].length-a[1].length)}
function res(r){let ativos=r.filter(a=>(a.sit||'ATIVO')==='ATIVO').length,f=r.reduce((s,a)=>s+a.faltas,0),p=r.reduce((s,a)=>s+a.pres,0);return{total:r.length,ativos,des:r.length-ativos,faltas:f,pct:p+f?Math.round(p/(p+f)*100):0}}
function htmlAlunos(tipo,mod,titulo,versao){
 let r=rows(mod),dt=new Date().toLocaleDateString('pt-BR',{day:'2-digit',month:'long',year:'numeric'}),nome=T[tipo]||'Relatório',mob=versao==='mobile',rr=res(r);
 let css=`<style>*{box-sizing:border-box}body{margin:0;padding:${mob?'12px':'28px'};background:radial-gradient(circle at 12% 0,rgba(47,128,237,.25),transparent 32%),linear-gradient(145deg,#020611,#07111F 48%,#030712);color:#EAF4FF;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Arial,sans-serif}.shell{max-width:1100px;margin:auto;background:linear-gradient(145deg,rgba(255,255,255,.055),rgba(255,255,255,.016)),rgba(8,19,36,.84);border:1px solid rgba(126,200,240,.18);border-radius:26px;box-shadow:0 26px 80px rgba(0,0,0,.42);overflow:hidden}.hero{padding:24px;background:linear-gradient(135deg,rgba(7,17,31,.96),rgba(16,40,70,.82));border-bottom:1px solid rgba(126,200,240,.16)}.badge{display:inline-block;padding:7px 12px;border-radius:999px;background:linear-gradient(135deg,#2F80ED,#22D3EE);font-size:11px;font-weight:900}.title{font-size:${mob?'24px':'30px'};font-weight:950;margin-top:8px}.sub{color:#9CB8D6;font-size:12px}.content{padding:${mob?'14px':'22px'}}.kpis{display:grid;grid-template-columns:repeat(${mob?'2':'4'},1fr);gap:10px;margin-bottom:16px}.kpi,.card{background:rgba(7,17,31,.76);border:1px solid rgba(126,200,240,.15);border-radius:18px;padding:14px;margin-bottom:14px;box-shadow:0 16px 40px rgba(0,0,0,.22)}.num{font-size:30px;font-weight:950;color:var(--c)}.txt{font-size:10px;color:#8FAACB;text-transform:uppercase;font-weight:900;letter-spacing:1px}.st{font-size:17px;font-weight:900;color:#7EC8F0;margin-bottom:12px}table{width:100%;border-collapse:collapse;font-size:12px;min-width:760px}th{background:#102846;color:#7EC8F0;text-align:left;padding:9px;font-size:10px;text-transform:uppercase}td{padding:9px;border-bottom:1px solid rgba(126,200,240,.1)}.table{overflow:auto}.tag{display:inline-flex;padding:4px 9px;border-radius:999px;font-size:10px;font-weight:900}.b{background:rgba(74,144,217,.14);color:#7EC8F0}.g{background:rgba(62,201,122,.14);color:#7EDBA8}.r{background:rgba(224,85,85,.14);color:#F08080}.p{background:rgba(155,89,182,.16);color:#D8A7ED}.route{display:grid;grid-template-columns:repeat(${mob?'1':'3'},1fr);gap:10px}.step{border:1px solid rgba(126,200,240,.15);border-radius:15px;padding:10px;background:rgba(255,255,255,.035)}@media(max-width:780px){.kpis{grid-template-columns:1fr 1fr}.route{grid-template-columns:1fr}.content{padding:14px}body{padding:10px}}</style>`;
 let body=`<div class="kpis"><div class="kpi" style="--c:#7EC8F0"><div class="num">${rr.total}</div><div class="txt">Alunos</div></div><div class="kpi" style="--c:#3EC97A"><div class="num">${rr.ativos}</div><div class="txt">Ativos</div></div><div class="kpi" style="--c:#E05555"><div class="num">${rr.faltas}</div><div class="txt">Faltas</div></div><div class="kpi" style="--c:#9B59B6"><div class="num">${rr.pct}%</div><div class="txt">Presença</div></div></div>`;
 let tabAl=()=>`<div class="table"><table><thead><tr><th>Aluno</th><th>Inscrição</th><th>Módulo ativo</th><th>Turma</th><th>Equipe</th><th>Situação</th><th>Presença</th><th>Faltas M1</th><th>Faltas M2</th><th>Faltas M3</th></tr></thead><tbody>${r.map(a=>`<tr><td><b>${a.nome}</b></td><td>${a.ins||'—'}</td><td><span class="tag b">${a.mod}</span></td><td>${a.turma}</td><td>${a.equipe}</td><td><span class="tag ${a.sit==='DESISTENTE'?'r':'g'}">${a.sit}</span></td><td><span class="tag p">${a.pct}%</span></td><td>${a.mods[0].f}</td><td>${a.mods[1].f}</td><td>${a.mods[2].f}</td></tr>`).join('')}</tbody></table></div>`;
 let tabGr=items=>`<div class="table"><table><thead><tr><th>Grupo</th><th>Alunos</th><th>Ativos</th><th>Desist.</th><th>Faltas</th><th>Presença</th></tr></thead><tbody>${items.map(([n,rs])=>{let x=res(rs);return`<tr><td><b>${n}</b></td><td>${x.total}</td><td><span class="tag g">${x.ativos}</span></td><td><span class="tag r">${x.des}</span></td><td>${x.faltas}</td><td><span class="tag p">${x.pct}%</span></td></tr>`}).join('')}</tbody></table></div>`;
 if(tipo==='alunos')body+=`<div class="card"><div class="st">Relatório geral dos alunos</div>${tabAl()}</div>`;
 if(tipo==='modulo')body+=`<div class="card"><div class="st">Relatório por módulo</div>${tabGr(grup(r,a=>a.mod))}</div>`;
 if(tipo==='turma')body+=`<div class="card"><div class="st">Relatório por turma</div>${tabGr(grup(r,a=>a.turma))}</div>`;
 if(tipo==='caminho')body+=r.map(a=>`<div class="card"><div class="st">${a.nome}</div><div class="sub">${a.equipe} · ${a.turma} · Módulo ativo: ${a.mod}</div><div class="route" style="margin-top:12px">${[1,2,3].map(m=>{let z=a.mods[m-1];return`<div class="step"><b>${MODULOS[m].nome}</b><div class="sub">${z.status}</div><div style="margin-top:8px"><span class="tag g">${z.p}/${z.t} pres.</span> <span class="tag r">${z.f} faltas</span> <span class="tag b">${z.pct}%</span></div></div>`}).join('')}</div></div>`).join('');
 return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${titulo} — ${nome}</title>${css}</head><body><main class="shell"><header class="hero"><div class="badge">${nome} · Versão ${versao==='web'?'Web':'Mobile'}</div><div class="title">${titulo}</div><div class="sub">Gerado em ${dt} · Instituto de Vencedores</div></header><section class="content">${body}</section></main></body></html>`;
}
window.montarMensagemWhats=function(link,porModulo,tipo){let linhas='📅 Relatório gerado';if(Array.isArray(porModulo)&&porModulo.length)linhas=porModulo.map(i=>semLabelCurto(i)+' - '+i.nomeModulo).join('\n');return`📊 *${tipo||'Relatório'} – Instituto de Vencedores*\n\n${linhas}\n\n🔗 Acesse pelo link:\n${link}`};
window.gerarRelatorioLink=async function(){
 let mod=document.getElementById('exp-modulo').value,titulo=document.getElementById('exp-titulo').value||'Instituto de Vencedores',tipo=(document.getElementById('exp-tipo')||{}).value||'visao',mods=mod==='todos'?[1,2,3]:[parseInt(mod)],html;
 if(tipo==='visao'){let data=buildReportData(mods);html=gerarHTMLMobile(data,titulo);if(relVersao==='web'){html=html.replace('<body>','<body class="rel-web">').replace('<style>','<style>body.rel-web{padding:28px 24px!important}body.rel-web .phone,body.rel-web .mobile-shell,body.rel-web .app,body.rel-web main{max-width:1100px!important;width:100%!important;margin-left:auto!important;margin-right:auto!important}body.rel-web .kpi-row,body.rel-web .cards,body.rel-web .grid{grid-template-columns:repeat(auto-fit,minmax(240px,1fr))!important}')}}else html=htmlAlunos(tipo,mod,titulo,relVersao);
 let ultima=detectarUltimaSemana(mods);toast('Gerando link, aguarde...⏳');
 try{let id='r'+Date.now().toString(36)+Math.random().toString(36).slice(2,6);let {getFirestore,doc,setDoc}=await import("https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js");await setDoc(doc(getFirestore(),"relatorios",id),{html,titulo,tipo:T[tipo],versao:relVersao,criadoEm:new Date().toISOString()});let link=`${location.origin}/relatorio?id=${id}`;document.getElementById('link-gerado').value=link;window._ultimaSemana=ultima;window._tipoRelatorioAtual=T[tipo];let prev=document.getElementById('whats-preview');if(prev)prev.textContent=montarMensagemWhats(link,ultima,window._tipoRelatorioAtual);document.getElementById('modal-link').style.display='flex';toast('Link gerado! ✓')}catch(e){console.error(e);toast('Erro ao gerar link. Tente novamente.',true)}
};
window.gerarRelatorio=function(){return gerarRelatorioLink()};
window.copiarLink=function(){let link=document.getElementById('link-gerado').value,msg=montarMensagemWhats(link,window._ultimaSemana||[],window._tipoRelatorioAtual||'Relatório');navigator.clipboard.writeText(msg).then(()=>toast('Mensagem copiada! ✓'))};
window.abrirWhatsApp=function(){let link=document.getElementById('link-gerado').value,msg=montarMensagemWhats(link,window._ultimaSemana||[],window._tipoRelatorioAtual||'Relatório');window.open('https://wa.me/?text='+encodeURIComponent(msg),'_blank')};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patchUI);else patchUI();
})();
